// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbOYQsmpXp02i6utllHxyaM0GsI0i4Lc',
    appId: '1:659290111643:android:5c434c667a2b9ea682903e',
    messagingSenderId: '659290111643',
    projectId: 'carbon-fora-a86fe',
    storageBucket: 'carbon-fora-a86fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTipuYmGPghfSDdpmlHZfgvix8Qa42yDc',
    appId: '1:659290111643:ios:d8d39c8291d1224082903e',
    messagingSenderId: '659290111643',
    projectId: 'carbon-fora-a86fe',
    storageBucket: 'carbon-fora-a86fe.firebasestorage.app',
    androidClientId: '659290111643-p691psqd1hfserlb3gl8ffkucnahqtua.apps.googleusercontent.com',
    iosClientId: '659290111643-e82dv1laorntc3tu516kq3jnot77f9n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonFora',
  );

}